### ISSUE TITLE
twitterアカウントでログインできるようにする

### ISSUE THREAD

**Issue by ghost** [SitAndGo/SitAndGo#10]
## 流れ
- まずSitAndGo独自アカウントの仕組みを実装するべき
- 各種SNSなどのアカウントでログインできるようにする場合は独自アカウントに紐付けを行う
- 上記はpassportを使って実装すればその後の拡張なども簡単に済む
## 参考
- http://passportjs.org/
- http://knimon-software.github.io/www.passportjs.org/
- http://d.hatena.ne.jp/pospome/20150608/1433757625
- http://liginc.co.jp/web/programming/node-js/165531

**Comment by kuriko** [comment]
個人情報持つの法務的につらいんでオリジナルのサインアップは無しでお願いします。

**Comment by ghost** [comment]
> オリジナルのサインアップは無し

はい
あくまで各種のSNSアカウントを紐付かせるためだけの物として実装しておきます

**Comment by ghost** [comment]
当初はこのissueとPRだけで独自アカウントの管理までやるつもりでしたが切り分けます
切り分け先は↑に出ているissueです
